.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH BCA-DUMP 1  "big-code-analysis 1.1.0" "big-code-analysis Manual"
.SH NAME
bca\-dump \- Dump the AST to stdout
.SH SYNOPSIS
\fBbca\-dump\fR [\fB\-\-line\-start\fR] [\fB\-\-line\-end\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Dump the AST to stdout
.SH OPTIONS
.TP
\fB\-\-line\-start\fR \fI<LINE_START>\fR
First line of the range to analyze (1\-based, inclusive)
.TP
\fB\-\-line\-end\fR \fI<LINE_END>\fR
Last line of the range to analyze (1\-based, inclusive)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
