.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH BCA-FIND 1  "big-code-analysis 0.1.0" "big-code-analysis Manual"
.SH NAME
bca\-find \- Find nodes of one or more types
.SH SYNOPSIS
\fBbca\-find\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINODES\fR> 
.SH DESCRIPTION
Find nodes of one or more types
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINODES\fR>
Node\-type names. Pass one or more, space\-separated
