.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH BCA-FUNCTIONS 1  "big-code-analysis 0.1.0" "big-code-analysis Manual"
.SH NAME
bca\-functions \- List functions/methods and their spans
.SH SYNOPSIS
\fBbca\-functions\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List functions/methods and their spans
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
