.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH BCA-STRIP-COMMENTS 1  "big-code-analysis 0.0.25" "big-code-analysis Manual"
.SH NAME
bca\-strip\-comments \- Remove comments from source files
.SH SYNOPSIS
\fBbca\-strip\-comments\fR [\fB\-\-in\-place\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove comments from source files
.SH OPTIONS
.TP
\fB\-\-in\-place\fR
Rewrite each input file in place instead of writing to stdout
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
