//! Help-text quality gates (issue #608).
//!
//! These pin the user-facing `--help` polish the help-text sweep
//! established, so a later edit that reintroduces issue-tracker
//! breadcrumbs, mangles the `--config` TOML example, or lets the
//! `--format` value-name drift back to `<OUTPUT_FORMAT>` fails CI rather
//! than shipping silently. Help is generated by clap at runtime, so the
//! assertions drive the real binary.

use assert_cmd::Command;
use predicates::prelude::*;

use crate::common;

fn cli() -> Command {
    common::bca_command()
}

/// Every subcommand whose `--help` users actually read. The parent
/// `bca --help` and the two `vcs` sub-subcommands are appended in the
/// loop below.
const SUBCOMMANDS: &[&[&str]] = &[
    &["metrics"],
    &["ops"],
    &["vcs"],
    &["report"],
    &["dump"],
    &["find"],
    &["count"],
    &["functions"],
    &["strip-comments"],
    &["preproc"],
    &["list-metrics"],
    &["check"],
    &["init"],
    &["diff-baseline"],
    &["diff"],
    &["exemptions"],
    &["vcs", "commit"],
    &["vcs", "trend"],
];

fn help_for(args: &[&str]) -> String {
    let output = cli()
        .args(args)
        .arg("--help")
        .output()
        .expect("spawn bca --help");
    assert!(
        output.status.success(),
        "`bca {} --help` should exit 0",
        args.join(" ")
    );
    String::from_utf8(output.stdout).expect("help is utf-8")
}

/// Scan `text` for a `#NNN` issue breadcrumb — a `#` immediately
/// followed by 2-4 digits. Version-like `1.2.3` text has no `#`, so it is
/// never matched. Returns the offending `#NNN` slice for the panic
/// message.
fn find_issue_reference(text: &str) -> Option<String> {
    let bytes = text.as_bytes();
    for (idx, &b) in bytes.iter().enumerate() {
        if b != b'#' {
            continue;
        }
        let digits = bytes[idx + 1..]
            .iter()
            .take_while(|c| c.is_ascii_digit())
            .count();
        if (2..=4).contains(&digits) {
            return Some(text[idx..idx + 1 + digits].to_string());
        }
    }
    None
}

/// No issue-tracker breadcrumb (`#539`, `issue #328`, `pre-#182`) may
/// reach user-facing help. They are provenance for maintainers and live
/// in `//` comments, never in the clap doc-comments clap renders.
#[test]
fn help_text_carries_no_issue_references() {
    let mut targets: Vec<Vec<&str>> = SUBCOMMANDS.iter().map(|s| s.to_vec()).collect();
    targets.push(Vec::new()); // the top-level `bca --help`

    for args in &targets {
        let help = help_for(args);
        let label = if args.is_empty() {
            "bca".to_string()
        } else {
            format!("bca {}", args.join(" "))
        };
        if let Some(found) = find_issue_reference(&help) {
            panic!(
                "`{label} --help` leaks issue reference {found:?}; move it into a `//` maintainer comment"
            );
        }
    }
}

/// The same `--format` flag must read `<FORMAT>` everywhere — the three
/// `output_format`-backed stragglers (`metrics` / `ops` / `check
/// --report-format`) used to leak the field name as `<OUTPUT_FORMAT>`.
#[test]
fn format_flags_use_format_value_name() {
    for (args, flag) in [
        (&["metrics"][..], "--format <FORMAT>"),
        (&["ops"][..], "--format <FORMAT>"),
        (&["check"][..], "--report-format <FORMAT>"),
    ] {
        let help = help_for(args);
        assert!(
            help.contains(flag),
            "`bca {} --help` should render `{flag}`, not `<OUTPUT_FORMAT>`",
            args.join(" ")
        );
        assert!(
            !help.contains("<OUTPUT_FORMAT>"),
            "`bca {} --help` still leaks the `<OUTPUT_FORMAT>` field name",
            args.join(" ")
        );
    }
}

/// The `--config` example must render as a readable indented block, not
/// the one-line smashed Markdown fence clap produced before
/// `verbatim_doc_comment` was applied.
#[test]
fn check_config_example_renders_as_block() {
    cli()
        .args(["check", "--help"])
        .assert()
        .success()
        // The table rows land on their own indented lines.
        .stdout(predicate::str::contains("    [thresholds]\n"))
        .stdout(predicate::str::contains("    cyclomatic = 15\n"))
        // The raw Markdown fence must never reach the rendered help.
        .stdout(predicate::str::contains("```").not());
}
