//! Baseline file for `bca check`: external record of currently-known
//! threshold offenders that the check is allowed to ignore until the
//! team gets around to fixing them. Companion to (not substitute for)
//! the in-source suppression markers from issue #98 — suppressions
//! express "exempt forever", baselines express "tech debt we're paying
//! down".
//!
//! The on-disk shape is TOML, sorted by `(path, start_line, function,
//! metric)` so diffs are reviewable. Each entry pins `(path, function,
//! start_line, metric, value)`; the filter is "current value <=
//! baseline value", so improvements pass silently and regressions
//! still fail.
//!
//! Path keys are canonicalised relative to an *anchor*: the directory
//! containing the baseline file (lexically resolved, no symlink
//! following). Write and read use the same anchor, so a baseline
//! generated by `bca check --paths .` matches a subsequent
//! `bca check --paths "$PWD"` byte-for-byte at the key level. See
//! [`normalize_path`] for the encoding pipeline.

use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::thresholds::Violation;

/// Schema version. Bump on breaking format changes.
///
/// History:
/// - v1 → v2: path-key percent-encoding made total (the UTF-8 fast
///   path now escapes `%`, so `src/é.rs` encodes as `src/%C3%A9.rs`).
/// - v2 → v3: path keys canonicalised relative to the baseline-file
///   anchor (issue #376). `--paths .`, `--paths src/`, and
///   `--paths "$PWD"` produce byte-identical baselines because every
///   path is resolved to an absolute, lexically-normalised form and
///   then stripped against the anchor before percent-encoding.
///
/// A v2 baseline is still accepted: each legacy entry's path string
/// is re-run through the v3 pipeline at load time, which is a no-op
/// for already-canonical ASCII paths and emits a one-time deprecation
/// warning so the user knows to refresh with `--write-baseline`.
pub(crate) const BASELINE_VERSION: u32 = 3;

/// Lowest legacy version still accepted at read time. Below this we
/// reject with a "regenerate" hint instead of silently mis-matching.
const LEGACY_MIN_VERSION: u32 = 2;

const HEADER: &str = "\
# bca baseline file. Generated by `bca check --write-baseline`.
# Listed offenders are filtered from threshold checks; a function that
# gets worse than its recorded value still fails. Refresh with
# `--write-baseline` when entries become stale.
#
# Path keys are relative to this file's directory (the anchor), so the
# baseline survives any `--paths` form (`.`, `src/`, `$PWD`, …).
";

/// Composite key into the baseline lookup. Owned strings because
/// deserialized entries don't borrow from anything; the `Violation`
/// path is normalized to a forward-slash `String` on construction so
/// baselines committed from Linux match the same tree analyzed on
/// Windows.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
struct Key {
    path: String,
    function: String,
    start_line: usize,
    metric: String,
}

/// One serialized entry. `path` is held as `String` (forward-slash
/// normalized) so the TOML is platform-neutral. Fields are
/// module-private; serde reaches them through the derived impls.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct BaselineEntry {
    path: String,
    function: String,
    start_line: usize,
    metric: String,
    /// Metric value at baseline time. `current > value` still fails
    /// (ratchet-down). Non-finite values are skipped at construction.
    value: f64,
}

/// Top-level baseline file. `version` is required; missing field is a
/// hard error so a truncated file isn't silently treated as empty.
///
/// `entries` is the only field reached from outside the module
/// (`run_check` reports the entry count after a `--write-baseline`).
///
/// `Default` is intentionally NOT derived: a default-constructed
/// `BaselineFile` would have `version: None` and render to TOML
/// without a version field, which `from_str` would then reject.
/// Construct explicitly with `Some(BASELINE_VERSION)` instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct BaselineFile {
    /// Schema version. Higher values mean the file was written by a
    /// newer bca and must be regenerated (or this bca upgraded).
    version: Option<u32>,
    #[serde(default, rename = "entry")]
    pub(crate) entries: Vec<BaselineEntry>,
}

/// In-memory lookup. Construction validates the schema version and
/// drops entries with non-finite values (defense in depth — `toml`
/// rejects nan/inf at the parser level, but a malicious or hand-edited
/// file could still try).
///
/// `anchor` is the lexically-absolute directory the baseline lives in
/// (see [`anchor_for`]). Every classify call canonicalises the
/// incoming violation path against the same anchor that the loader
/// used, so the key shape matches regardless of which `--paths` form
/// the analyser was invoked with.
#[derive(Debug)]
pub(crate) struct Baseline {
    by_key: HashMap<Key, f64>,
    anchor: PathBuf,
}

impl Baseline {
    /// Parse a TOML baseline document keyed against `anchor` (typically
    /// derived via [`anchor_for`] from the baseline file's own path).
    /// Errors are user-facing strings suitable for `die_io`.
    ///
    /// v2 baselines are accepted for backwards compatibility: each
    /// legacy entry's stored path is re-run through the v3 pipeline at
    /// load time so the path-stickiness fix applies retroactively. A
    /// one-time deprecation warning is emitted on stderr recommending
    /// `--write-baseline` to upgrade the file in place. v2 entries
    /// whose stored path was already percent-encoded (non-ASCII or
    /// special characters) may not survive the migration — those
    /// surface as `New` until the user refreshes.
    pub(crate) fn from_str(text: &str, anchor: &Path) -> Result<Self, String> {
        let file: BaselineFile =
            toml::from_str(text).map_err(|e| format!("malformed baseline TOML: {e}"))?;
        let version = file
            .version
            .ok_or_else(|| "baseline missing version field".to_string())?;
        if !(LEGACY_MIN_VERSION..=BASELINE_VERSION).contains(&version) {
            return Err(format!(
                "baseline version {version} is not supported by this bca \
                 (expected {LEGACY_MIN_VERSION}..={BASELINE_VERSION}); \
                 regenerate with `bca check --write-baseline` or upgrade bca"
            ));
        }
        let is_legacy = version < BASELINE_VERSION;
        if is_legacy {
            eprintln!(
                "bca: baseline is v{version}; refresh with `--write-baseline` \
                 to migrate to v{BASELINE_VERSION} (canonical paths, no \
                 `--paths`-form stickiness)"
            );
        }
        let anchor = anchor.to_path_buf();
        let mut by_key = HashMap::with_capacity(file.entries.len());
        for e in file.entries {
            // Skip non-finite and negative values. Non-finite is the
            // pre-existing defense against hand-edited files (TOML's
            // parser also rejects nan/inf). Negative is the same idea
            // for the rendered-tag path: `format_regressed_tag` divides
            // by `recorded` to compute `+N%`, and a negative `recorded`
            // produces a double-signed `[regr +-N%]` tag. Metric
            // extractors never emit negative values, so the only way
            // an entry can be negative is hand-editing — silently
            // drop and treat the entry as if missing (the violation
            // will surface as `New`).
            if !e.value.is_finite() || e.value < 0.0 {
                continue;
            }
            // v3 stored paths are already canonical (the writer ran
            // them through `normalize_path`). Running them a second
            // time would double-encode pre-existing `%XX` escapes
            // produced by the non-UTF-8 branches. v2 paths predate
            // the anchor-relative form and get re-canonicalised here
            // as a best-effort migration; non-ASCII v2 entries that
            // already contain `%XX` will double-encode and surface
            // as `New` on the next run, which is the documented
            // "refresh with --write-baseline" path.
            let path = if is_legacy {
                normalize_path(&anchor, Path::new(&e.path))
            } else {
                e.path
            };
            by_key.insert(
                Key {
                    path,
                    function: e.function,
                    start_line: e.start_line,
                    metric: e.metric,
                },
                e.value,
            );
        }
        Ok(Self { by_key, anchor })
    }

    /// Classify a violation against the baseline. The three states
    /// drive both the filter (`Covered` drops, `Regressed` / `New`
    /// keep) and the stderr tag prefix in `run_check`. Keeping the
    /// recorded value on the kept variant means the renderer can
    /// compute the `+N%` regression magnitude without re-keying.
    ///
    /// NaN current values are classified as `Regressed` rather than
    /// `Covered`: a NaN metric is degenerate (typically a Halstead
    /// edge case on trivial functions) and falling through to the
    /// `<=` arm would silently mark it covered because `NaN <= x` is
    /// false. The explicit guard makes the intent obvious at the
    /// call site, and the renderer keys off `value.is_nan()` to emit
    /// `[regr NaN]` instead of dividing by `recorded`.
    pub(crate) fn classify(&self, v: &Violation) -> Coverage {
        let key = Key {
            path: normalize_path(&self.anchor, &v.path),
            function: v.function.clone(),
            start_line: v.start_line,
            metric: v.metric.to_string(),
        };
        match self.by_key.get(&key) {
            None => Coverage::New,
            Some(&recorded) if v.value.is_nan() => Coverage::Regressed { recorded },
            Some(&recorded) if v.value <= recorded => Coverage::Covered { recorded },
            Some(&recorded) => Coverage::Regressed { recorded },
        }
    }
}

/// Outcome of comparing a single violation against the loaded baseline.
///
/// `Covered` drops the violation from the kept set (the function has
/// not worsened past its recorded value, and we're explicitly tolerating
/// it as ratchet-down tech debt). `Regressed` and `New` keep the
/// violation and carry enough information for the stderr renderer to
/// prefix a `[regr +N%]` / `[new]` tag at emit time.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum Coverage {
    /// Baseline entry exists and current value has not worsened.
    /// `recorded` is the value pinned in the baseline file.
    Covered { recorded: f64 },
    /// Baseline entry exists but the current value has worsened.
    /// `recorded` is the prior value; the renderer subtracts to
    /// compute the regression magnitude.
    Regressed { recorded: f64 },
    /// No baseline entry for this `(path, function, start_line, metric)`
    /// tuple — the violation is new since the baseline was written.
    New,
}

/// Build a `BaselineFile` from a list of violations, keyed against
/// `anchor` (typically derived via [`anchor_for`] from the baseline
/// file's path). Skips entries whose `value` is non-finite (degenerate
/// Halstead inputs can produce NaN/Inf, which TOML cannot serialize)
/// and emits a stderr warning per occurrence. Entries are sorted by
/// `(path, start_line, function, metric)` so the rendered output is
/// deterministic and diff-friendly.
pub(crate) fn from_violations(violations: Vec<Violation>, anchor: &Path) -> BaselineFile {
    let mut entries: Vec<BaselineEntry> = violations
        .into_iter()
        .filter_map(|v| {
            if !v.value.is_finite() {
                eprintln!(
                    "warning: skipping non-finite value for {}:{}-{}: {} = {}",
                    v.path.display(),
                    v.start_line,
                    v.end_line,
                    v.metric,
                    v.value,
                );
                return None;
            }
            Some(BaselineEntry {
                path: normalize_path(anchor, &v.path),
                function: v.function,
                start_line: v.start_line,
                metric: v.metric.to_string(),
                value: v.value,
            })
        })
        .collect();
    entries.sort_by(|a, b| {
        a.path
            .cmp(&b.path)
            .then(a.start_line.cmp(&b.start_line))
            .then(a.function.cmp(&b.function))
            .then(a.metric.cmp(&b.metric))
    });
    BaselineFile {
        version: Some(BASELINE_VERSION),
        entries,
    }
}

/// Render a `BaselineFile` to a TOML string with the standard comment
/// header prepended. Output is deterministic byte-for-byte for the
/// same input (TOML's f64 formatter is round-trip stable, struct field
/// order is fixed by `#[derive(Serialize)]` declaration order).
pub(crate) fn render(file: &BaselineFile) -> Result<String, toml::ser::Error> {
    let body = toml::to_string(file)?;
    Ok(format!("{HEADER}{body}"))
}

/// Derive the canonical anchor for a baseline file at `baseline_path`:
/// the lexically-absolute directory the file lives in. Used at both
/// write and read time so the key shape is independent of `--paths`
/// form, working directory drift, or whether the path was passed
/// relative or absolute.
///
/// Lexical, not symlink-following: `bca` should not surprise users by
/// resolving `src/` through a symlinked directory. The cost is that a
/// baseline written via a symlinked invocation and read via the real
/// path (or vice-versa) does not match — but that mirrors how every
/// other tool (cargo, git) treats workdir identity.
pub(crate) fn anchor_for(baseline_path: &Path) -> PathBuf {
    let abs = std::path::absolute(baseline_path).unwrap_or_else(|_| baseline_path.to_path_buf());
    let mut abs = lexical_normalize(&abs);
    // `pop` returns false if the path is already a root or empty; in
    // that degenerate case the path itself becomes the anchor.
    abs.pop();
    abs
}

/// Lexically normalise `p` by folding `.` and `..` components without
/// touching the filesystem. `..` past the root (or a leading prefix on
/// Windows) is preserved literally — the alternative is to silently
/// rewrite paths that escape the anchor, which would break identity
/// for legitimate sibling-of-anchor entries.
fn lexical_normalize(p: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for c in p.components() {
        match c {
            Component::Prefix(_) | Component::RootDir | Component::Normal(_) => out.push(c),
            Component::CurDir => {}
            Component::ParentDir => {
                let last_is_normal =
                    matches!(out.components().next_back(), Some(Component::Normal(_)));
                if last_is_normal {
                    out.pop();
                } else {
                    out.push(c);
                }
            }
        }
    }
    out
}

/// Normalize a path for use as a baseline identity key.
///
/// 1. The path is made lexically absolute (using `anchor` as the base
///    directory when relative) and `.` / `..` components are folded.
/// 2. If the result is under `anchor`, the anchor prefix is stripped so
///    the key form is `src/foo.rs` rather than `{anchor}/src/foo.rs`.
///    Paths outside the anchor (rare; e.g. a baseline that records
///    files from a sibling crate) keep their absolute form.
/// 3. The resulting `OsStr` is fed through the byte-level
///    percent-encoder for TOML safety (backslash → forward slash,
///    non-unreserved bytes → `%XX`, Windows unpaired surrogates →
///    `%uHHHH`). The encoding is injective: distinct byte sequences
///    produce distinct strings.
///
/// Non-UTF-8 paths cannot be represented verbatim in a TOML string
/// (TOML mandates UTF-8). Falling back to `Path::display()` would
/// replace every invalid byte with U+FFFD and collapse distinct paths
/// onto the same key — exactly the lossy identity collision we have to
/// avoid. The per-byte encoder preserves identity by emitting `%XX` for
/// every byte not in the unreserved path set.
fn normalize_path(anchor: &Path, p: &Path) -> String {
    // Resolve to an absolute, lexically-normalised PathBuf so the key
    // is independent of CWD and the `--paths` form the user passed.
    // `std::path::absolute` falls back to a no-op for empty paths; we
    // still want to strip the anchor in that case.
    let base = anchor;
    let abs = if p.is_absolute() {
        lexical_normalize(p)
    } else {
        let joined = if base.as_os_str().is_empty() {
            p.to_path_buf()
        } else {
            base.join(p)
        };
        lexical_normalize(&joined)
    };
    let stripped = abs.strip_prefix(base).unwrap_or(&abs);
    encode_os_path(stripped.as_os_str())
}

/// Encode an OS string into a TOML-safe key. Routes through the
/// UTF-8 fast path when possible (still per-byte percent-encoded for
/// `%` safety), falls back to the platform-specific byte/WTF-16
/// encoders for non-UTF-8 paths. See [`normalize_path`] for the
/// injectivity guarantee.
fn encode_os_path(s: &std::ffi::OsStr) -> String {
    match s.to_str() {
        Some(s) => {
            let mut out = String::with_capacity(s.len());
            for b in s.bytes() {
                let b = if b == b'\\' { b'/' } else { b };
                push_percent_encoded_byte(&mut out, b);
            }
            out
        }
        None => encode_non_utf8_os_str(s),
    }
}

#[cfg(unix)]
fn encode_non_utf8_os_str(s: &std::ffi::OsStr) -> String {
    use std::os::unix::ffi::OsStrExt;
    percent_encode_path_bytes(s.as_bytes())
}

#[cfg(windows)]
fn encode_non_utf8_os_str(s: &std::ffi::OsStr) -> String {
    use std::os::windows::ffi::OsStrExt;
    percent_encode_wtf16(s.encode_wide())
}

#[cfg(not(any(unix, windows)))]
fn encode_non_utf8_os_str(s: &std::ffi::OsStr) -> String {
    // Exotic targets (wasm, etc.) where neither `OsStrExt` is available.
    // Reuse the per-byte encoder on the lossy UTF-8 form so output is
    // still TOML-safe; injectivity is best-effort here because the
    // platform itself has already destroyed the original bytes via
    // `to_string_lossy`. Prefix with U+FFFD so the key can never collide
    // with one produced through the `to_str()` branch above.
    let mut out = String::from("\u{FFFD}");
    for &b in s.to_string_lossy().as_bytes() {
        push_percent_encoded_byte(&mut out, b);
    }
    out
}

/// Percent-encode the raw bytes of a non-UTF-8 path so the result is
/// (1) valid UTF-8 (required by TOML), (2) injective for distinct byte
/// sequences (required to keep baseline identities from collapsing),
/// and (3) human-recognizable for the common case where most bytes are
/// printable ASCII path characters. The unreserved set mirrors the
/// "safe for use in a filename" subset of RFC 3986 unreserved with
/// `/` added (path separator) and `%` excluded (escape introducer).
#[cfg(unix)]
fn percent_encode_path_bytes(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        push_percent_encoded_byte(&mut out, b);
    }
    out
}

/// Append a single byte to `out`, either verbatim (if it falls in the
/// unreserved path set) or as `%XX` (uppercase hex). The `%` byte
/// itself is not unreserved, so the output is unambiguous: every `%`
/// in the result was emitted by this function and is followed by
/// either two hex digits (from this function) or `u` followed by four
/// hex digits (from [`percent_encode_wtf16`]).
fn push_percent_encoded_byte(out: &mut String, b: u8) {
    use std::fmt::Write;
    let is_unreserved = b.is_ascii_alphanumeric()
        || matches!(
            b,
            b'-' | b'_' | b'.' | b'~' | b'/' | b':' | b'+' | b',' | b' '
        );
    if is_unreserved {
        out.push(b as char);
    } else {
        // Writing to a String can only fail on allocation failure, which
        // already panics in the standard library.
        let _ = write!(out, "%{b:02X}");
    }
}

/// Percent-encode a WTF-16 code-unit sequence into a TOML-safe UTF-8
/// string. Valid scalar values are encoded as their UTF-8 bytes through
/// [`push_percent_encoded_byte`]; unpaired surrogates are emitted as
/// `%uHHHH` (uppercase 4-digit hex), a form the byte encoder never
/// produces. The result is:
///
/// 1. **Injective**: every code unit maps to a distinct token (either
///    a sequence of `%XX` byte escapes / unreserved bytes for a paired
///    scalar, or one `%uHHHH` for an unpaired surrogate). Two distinct
///    WTF-16 sequences therefore always produce distinct strings.
/// 2. **Stable**: deterministic; no allocation order or hashing
///    influences output.
/// 3. **Human-debuggable enough**: ASCII path components survive
///    unchanged.
///
/// Exposed at `pub(crate)` purely so the unit tests can drive it with
/// synthetic input on any platform (the production caller is
/// `#[cfg(windows)]` only).
#[cfg(any(windows, test))]
pub(crate) fn percent_encode_wtf16(units: impl IntoIterator<Item = u16>) -> String {
    use std::fmt::Write;

    let mut out = String::new();
    let mut buf = [0u8; 4];
    for r in char::decode_utf16(units) {
        match r {
            Ok(c) => {
                for &b in c.encode_utf8(&mut buf).as_bytes() {
                    push_percent_encoded_byte(&mut out, b);
                }
            }
            Err(e) => {
                let _ = write!(out, "%u{:04X}", e.unpaired_surrogate());
            }
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::float_cmp)] // Test asserts compare bit-exact baseline values.
#[path = "baseline_tests.rs"]
mod tests;
