//! Baseline file for `bca check`: external record of currently-known
//! threshold offenders that the check is allowed to ignore until the
//! team gets around to fixing them. Companion to (not substitute for)
//! the in-source suppression markers from issue #98 — suppressions
//! express "exempt forever", baselines express "tech debt we're paying
//! down".
//!
//! The on-disk shape is TOML, sorted by `(path, start_line, function,
//! metric)` so diffs are reviewable. Each entry pins `(path, function,
//! start_line, metric, value)`; the filter is "current value <=
//! baseline value", so improvements pass silently and regressions
//! still fail.

use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::thresholds::Violation;

/// Schema version. Bump on breaking format changes.
///
/// Bumped from 1 to 2 when path-key percent-encoding was made total
/// (the UTF-8 fast path now escapes `%`, so a path like `src/é.rs`
/// encodes as `src/%C3%A9.rs` instead of the literal). Existing v1
/// baselines with non-ASCII or `%`-bearing paths must be regenerated;
/// the version mismatch surfaces the "regenerate" hint from
/// [`Baseline::from_str`] rather than silently mis-matching.
pub(crate) const BASELINE_VERSION: u32 = 2;

const HEADER: &str = "\
# bca baseline file. Generated by `bca check --write-baseline`.
# Listed offenders are filtered from threshold checks; a function that
# gets worse than its recorded value still fails. Refresh with
# `--write-baseline` when entries become stale.
";

/// Composite key into the baseline lookup. Owned strings because
/// deserialized entries don't borrow from anything; the `Violation`
/// path is normalized to a forward-slash `String` on construction so
/// baselines committed from Linux match the same tree analyzed on
/// Windows.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
struct Key {
    path: String,
    function: String,
    start_line: usize,
    metric: String,
}

/// One serialized entry. `path` is held as `String` (forward-slash
/// normalized) so the TOML is platform-neutral. Fields are
/// module-private; serde reaches them through the derived impls.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct BaselineEntry {
    path: String,
    function: String,
    start_line: usize,
    metric: String,
    /// Metric value at baseline time. `current > value` still fails
    /// (ratchet-down). Non-finite values are skipped at construction.
    value: f64,
}

/// Top-level baseline file. `version` is required; missing field is a
/// hard error so a truncated file isn't silently treated as empty.
///
/// `entries` is the only field reached from outside the module
/// (`run_check` reports the entry count after a `--write-baseline`).
///
/// `Default` is intentionally NOT derived: a default-constructed
/// `BaselineFile` would have `version: None` and render to TOML
/// without a version field, which `from_str` would then reject.
/// Construct explicitly with `Some(BASELINE_VERSION)` instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct BaselineFile {
    /// Schema version. Higher values mean the file was written by a
    /// newer bca and must be regenerated (or this bca upgraded).
    version: Option<u32>,
    #[serde(default, rename = "entry")]
    pub(crate) entries: Vec<BaselineEntry>,
}

/// In-memory lookup. Construction validates the schema version and
/// drops entries with non-finite values (defense in depth — `toml`
/// rejects nan/inf at the parser level, but a malicious or hand-edited
/// file could still try).
#[derive(Debug)]
pub(crate) struct Baseline {
    by_key: HashMap<Key, f64>,
}

impl Baseline {
    /// Parse a TOML baseline document. Errors are user-facing strings
    /// suitable for `die_io`.
    pub(crate) fn from_str(text: &str) -> Result<Self, String> {
        let file: BaselineFile =
            toml::from_str(text).map_err(|e| format!("malformed baseline TOML: {e}"))?;
        let version = file
            .version
            .ok_or_else(|| "baseline missing version field".to_string())?;
        if version != BASELINE_VERSION {
            return Err(format!(
                "baseline version {version} is not supported by this bca \
                 (expected {BASELINE_VERSION}); regenerate with \
                 `bca check --write-baseline` or upgrade bca"
            ));
        }
        let mut by_key = HashMap::with_capacity(file.entries.len());
        for e in file.entries {
            // Skip non-finite and negative values. Non-finite is the
            // pre-existing defense against hand-edited files (TOML's
            // parser also rejects nan/inf). Negative is the same idea
            // for the rendered-tag path: `format_regressed_tag` divides
            // by `recorded` to compute `+N%`, and a negative `recorded`
            // produces a double-signed `[regr +-N%]` tag. Metric
            // extractors never emit negative values, so the only way
            // an entry can be negative is hand-editing — silently
            // drop and treat the entry as if missing (the violation
            // will surface as `New`).
            if !e.value.is_finite() || e.value < 0.0 {
                continue;
            }
            by_key.insert(
                Key {
                    path: e.path,
                    function: e.function,
                    start_line: e.start_line,
                    metric: e.metric,
                },
                e.value,
            );
        }
        Ok(Self { by_key })
    }

    /// Classify a violation against the baseline. The three states
    /// drive both the filter (`Covered` drops, `Regressed` / `New`
    /// keep) and the stderr tag prefix in `run_check`. Keeping the
    /// recorded value on the kept variant means the renderer can
    /// compute the `+N%` regression magnitude without re-keying.
    ///
    /// NaN current values are classified as `Regressed` rather than
    /// `Covered`: a NaN metric is degenerate (typically a Halstead
    /// edge case on trivial functions) and falling through to the
    /// `<=` arm would silently mark it covered because `NaN <= x` is
    /// false. The explicit guard makes the intent obvious at the
    /// call site, and the renderer keys off `value.is_nan()` to emit
    /// `[regr NaN]` instead of dividing by `recorded`.
    pub(crate) fn classify(&self, v: &Violation) -> Coverage {
        let key = Key {
            path: normalize_path(&v.path),
            function: v.function.clone(),
            start_line: v.start_line,
            metric: v.metric.to_string(),
        };
        match self.by_key.get(&key) {
            None => Coverage::New,
            Some(&recorded) if v.value.is_nan() => Coverage::Regressed { recorded },
            Some(&recorded) if v.value <= recorded => Coverage::Covered { recorded },
            Some(&recorded) => Coverage::Regressed { recorded },
        }
    }
}

/// Outcome of comparing a single violation against the loaded baseline.
///
/// `Covered` drops the violation from the kept set (the function has
/// not worsened past its recorded value, and we're explicitly tolerating
/// it as ratchet-down tech debt). `Regressed` and `New` keep the
/// violation and carry enough information for the stderr renderer to
/// prefix a `[regr +N%]` / `[new]` tag at emit time.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum Coverage {
    /// Baseline entry exists and current value has not worsened.
    /// `recorded` is the value pinned in the baseline file.
    Covered { recorded: f64 },
    /// Baseline entry exists but the current value has worsened.
    /// `recorded` is the prior value; the renderer subtracts to
    /// compute the regression magnitude.
    Regressed { recorded: f64 },
    /// No baseline entry for this `(path, function, start_line, metric)`
    /// tuple — the violation is new since the baseline was written.
    New,
}

/// Build a `BaselineFile` from a list of violations. Skips entries
/// whose `value` is non-finite (degenerate Halstead inputs can produce
/// NaN/Inf, which TOML cannot serialize) and emits a stderr warning
/// per occurrence. Entries are sorted by
/// `(path, start_line, function, metric)` so the rendered output is
/// deterministic and diff-friendly.
pub(crate) fn from_violations(violations: Vec<Violation>) -> BaselineFile {
    let mut entries: Vec<BaselineEntry> = violations
        .into_iter()
        .filter_map(|v| {
            if !v.value.is_finite() {
                eprintln!(
                    "warning: skipping non-finite value for {}:{}-{}: {} = {}",
                    v.path.display(),
                    v.start_line,
                    v.end_line,
                    v.metric,
                    v.value,
                );
                return None;
            }
            Some(BaselineEntry {
                path: normalize_path(&v.path),
                function: v.function,
                start_line: v.start_line,
                metric: v.metric.to_string(),
                value: v.value,
            })
        })
        .collect();
    entries.sort_by(|a, b| {
        a.path
            .cmp(&b.path)
            .then(a.start_line.cmp(&b.start_line))
            .then(a.function.cmp(&b.function))
            .then(a.metric.cmp(&b.metric))
    });
    BaselineFile {
        version: Some(BASELINE_VERSION),
        entries,
    }
}

/// Render a `BaselineFile` to a TOML string with the standard comment
/// header prepended. Output is deterministic byte-for-byte for the
/// same input (TOML's f64 formatter is round-trip stable, struct field
/// order is fixed by `#[derive(Serialize)]` declaration order).
pub(crate) fn render(file: &BaselineFile) -> Result<String, toml::ser::Error> {
    let body = toml::to_string(file)?;
    Ok(format!("{HEADER}{body}"))
}

/// Normalize a path for use as a baseline identity key. Backslashes are
/// rewritten to forward slashes so a baseline committed on one OS
/// matches the same tree analyzed on another.
///
/// Non-UTF-8 paths cannot be represented verbatim in a TOML string
/// (TOML mandates UTF-8). Falling back to `Path::display()` would
/// replace every invalid byte with U+FFFD and collapse distinct paths
/// onto the same key — exactly the lossy identity collision we have to
/// avoid. Instead:
///
/// - The UTF-8 branch maps `\` -> `/` on the byte view and then runs
///   the same per-byte percent encoder used by the non-UTF-8 branches.
///   `%` itself is not in the unreserved set, so a UTF-8 path
///   containing the literal text `%FF` becomes `%25FF` and cannot
///   collide with a non-UTF-8 path that contains the byte `0xFF` (which
///   encodes to `%FF`). The cost is `%XX` escapes for any non-ASCII or
///   reserved byte in the TOML output.
/// - On Unix we read the raw bytes via `OsStrExt` and percent-encode
///   (`%XX`) every byte that is not a printable ASCII path character.
/// - On Windows we walk the WTF-16 code units via `encode_wide`,
///   decode valid scalar values to UTF-8 (then per-byte encode), and
///   emit `%uHHHH` for unpaired surrogates. The `%u` marker is
///   disjoint from the `%XX` two-hex-digit form, so the encoding is
///   unambiguous and injective.
///
/// All three branches feed bytes through the same per-byte encoder, so
/// a clean ASCII path produces the same key on either platform. Exotic
/// targets (wasm, etc.) where neither `OsStrExt` flavour is available
/// fall back to a `to_string_lossy()` form prefixed with U+FFFD; that
/// prefix is the marker the `to_str()` branch never emits, so the
/// fallback can never collide with a clean-UTF-8 key.
fn normalize_path(p: &Path) -> String {
    match p.to_str() {
        Some(s) => {
            let mut out = String::with_capacity(s.len());
            for b in s.bytes() {
                let b = if b == b'\\' { b'/' } else { b };
                push_percent_encoded_byte(&mut out, b);
            }
            out
        }
        None => encode_non_utf8_path(p),
    }
}

#[cfg(unix)]
fn encode_non_utf8_path(p: &Path) -> String {
    use std::os::unix::ffi::OsStrExt;
    percent_encode_path_bytes(p.as_os_str().as_bytes())
}

#[cfg(windows)]
fn encode_non_utf8_path(p: &Path) -> String {
    use std::os::windows::ffi::OsStrExt;
    percent_encode_wtf16(p.as_os_str().encode_wide())
}

#[cfg(not(any(unix, windows)))]
fn encode_non_utf8_path(p: &Path) -> String {
    // Exotic targets (wasm, etc.) where neither `OsStrExt` is available.
    // Reuse the per-byte encoder on the lossy UTF-8 form so output is
    // still TOML-safe; injectivity is best-effort here because the
    // platform itself has already destroyed the original bytes via
    // `to_string_lossy`. Prefix with U+FFFD so the key can never collide
    // with one produced through the `to_str()` branch above.
    let mut out = String::from("\u{FFFD}");
    for &b in p.to_string_lossy().as_bytes() {
        push_percent_encoded_byte(&mut out, b);
    }
    out
}

/// Percent-encode the raw bytes of a non-UTF-8 path so the result is
/// (1) valid UTF-8 (required by TOML), (2) injective for distinct byte
/// sequences (required to keep baseline identities from collapsing),
/// and (3) human-recognizable for the common case where most bytes are
/// printable ASCII path characters. The unreserved set mirrors the
/// "safe for use in a filename" subset of RFC 3986 unreserved with
/// `/` added (path separator) and `%` excluded (escape introducer).
#[cfg(unix)]
fn percent_encode_path_bytes(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        push_percent_encoded_byte(&mut out, b);
    }
    out
}

/// Append a single byte to `out`, either verbatim (if it falls in the
/// unreserved path set) or as `%XX` (uppercase hex). The `%` byte
/// itself is not unreserved, so the output is unambiguous: every `%`
/// in the result was emitted by this function and is followed by
/// either two hex digits (from this function) or `u` followed by four
/// hex digits (from [`percent_encode_wtf16`]).
fn push_percent_encoded_byte(out: &mut String, b: u8) {
    use std::fmt::Write;
    let is_unreserved = b.is_ascii_alphanumeric()
        || matches!(
            b,
            b'-' | b'_' | b'.' | b'~' | b'/' | b':' | b'+' | b',' | b' '
        );
    if is_unreserved {
        out.push(b as char);
    } else {
        // Writing to a String can only fail on allocation failure, which
        // already panics in the standard library.
        let _ = write!(out, "%{b:02X}");
    }
}

/// Percent-encode a WTF-16 code-unit sequence into a TOML-safe UTF-8
/// string. Valid scalar values are encoded as their UTF-8 bytes through
/// [`push_percent_encoded_byte`]; unpaired surrogates are emitted as
/// `%uHHHH` (uppercase 4-digit hex), a form the byte encoder never
/// produces. The result is:
///
/// 1. **Injective**: every code unit maps to a distinct token (either
///    a sequence of `%XX` byte escapes / unreserved bytes for a paired
///    scalar, or one `%uHHHH` for an unpaired surrogate). Two distinct
///    WTF-16 sequences therefore always produce distinct strings.
/// 2. **Stable**: deterministic; no allocation order or hashing
///    influences output.
/// 3. **Human-debuggable enough**: ASCII path components survive
///    unchanged.
///
/// Exposed at `pub(crate)` purely so the unit tests can drive it with
/// synthetic input on any platform (the production caller is
/// `#[cfg(windows)]` only).
#[cfg(any(windows, test))]
pub(crate) fn percent_encode_wtf16(units: impl IntoIterator<Item = u16>) -> String {
    use std::fmt::Write;

    let mut out = String::new();
    let mut buf = [0u8; 4];
    for r in char::decode_utf16(units) {
        match r {
            Ok(c) => {
                for &b in c.encode_utf8(&mut buf).as_bytes() {
                    push_percent_encoded_byte(&mut out, b);
                }
            }
            Err(e) => {
                let _ = write!(out, "%u{:04X}", e.unpaired_surrogate());
            }
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::float_cmp)] // Test asserts compare bit-exact baseline values.
#[path = "baseline_tests.rs"]
mod tests;
