//! Shared provenance footer for the AST report (issue #680).
//!
//! Both the Markdown and HTML AST reports close with one provenance line so
//! a reader of a detached artifact — a PR comment, a Pages deployment, a file
//! attached to a ticket — can tell what was scanned, with which `bca`
//! version, and whether suppression markers were honored. The last point is
//! load-bearing: hotspot-table membership depends on suppression policy, so
//! two reports over the same tree can legitimately differ, and without the
//! footer that difference looks like a bug. The VCS section already carries
//! its own provenance line (`crate::vcs_report::provenance`); this is the AST
//! report's equivalent.
//!
//! The date is reproducible-build friendly: it honors `SOURCE_DATE_EPOCH`
//! (the reproducible-builds standard) when set, otherwise the wall clock.
//! Snapshot tests redact the rendered date so they stay deterministic without
//! a bespoke `--date` flag.

// The civil-date conversion (`civil_from_days`) is Howard Hinnant's bounded
// integer algorithm; every cast is range-checked by the algorithm's domain
// (day-of-era in `[0, 146096]`, day/month in `[1, 31]`/`[1, 12]`). The
// wall-clock seconds cast tops out far below `i64::MAX`. Allowing the casts at
// module scope keeps the algorithm legible.
#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::unnecessary_cast
)]

use std::fmt::Write as _;

use big_code_analysis::SuppressionPolicy;

use crate::html_report::escape_html;
use crate::markdown_report::hotspot::cap;

/// The provenance facts a report footer states. Borrowed so the command layer
/// can assemble it from CLI args without extra allocation.
pub(crate) struct Provenance<'a> {
    /// `bca` package version (`CARGO_PKG_VERSION`).
    pub(crate) version: &'a str,
    /// `YYYY-MM-DD` generation date (UTC), already resolved (see
    /// [`resolved_date`]).
    pub(crate) date: &'a str,
    /// The CLI seed paths the user passed (what they asked to scan), not every
    /// walked file — compact and meaningful. Pre-joined for display.
    pub(crate) paths: &'a str,
    /// The resolved `--top` value (`0` = all).
    pub(crate) top: usize,
    /// Whether in-source suppression markers were honored (the default) or
    /// ignored (`--no-suppress`).
    pub(crate) policy: SuppressionPolicy,
}

impl Provenance<'_> {
    /// The per-table cap phrasing, mirroring the hotspot title clause: a
    /// concrete `top N` when capped, `all entries` when `--top 0`.
    fn top_phrase(&self) -> String {
        match cap(self.top) {
            Some(n) => format!("top {n} per table"),
            None => "all entries per table".to_owned(),
        }
    }

    /// `honored` / `ignored`, the word the footer uses for the suppression
    /// state.
    fn suppression_word(&self) -> &'static str {
        match self.policy {
            SuppressionPolicy::Honor => "honored",
            SuppressionPolicy::Ignore => "ignored",
        }
    }

    /// The footer sentence, with the user-controlled `paths` value passed
    /// through `paths_render` so each format neutralizes its own active
    /// characters. The static text (`version`, `date`, top/suppression
    /// phrasing) is format-safe — semver, digits, and fixed words — so only
    /// `paths` needs per-format treatment.
    fn sentence(&self, paths_render: impl Fn(&str) -> String) -> String {
        format!(
            "Generated by bca {} on {} over {} \u{2014} {}, suppression markers {}.",
            self.version,
            self.date,
            paths_render(self.paths),
            self.top_phrase(),
            self.suppression_word(),
        )
    }
}

/// Append the Markdown provenance footer: an italic line under a thematic
/// break so it reads as a footnote rather than report content. The seed
/// `paths` are wrapped in a backtick code span (via `escape_name`) so a path
/// containing `_`/`*`/`` ` `` cannot leak into the surrounding `_..._`
/// emphasis (issue #848); the rest of the sentence is literal.
pub(crate) fn push_markdown_footer(out: &mut String, prov: &Provenance<'_>) {
    let _ = writeln!(out, "\n---\n");
    let _ = writeln!(
        out,
        "_{}_",
        prov.sentence(crate::markdown_report::escape_name)
    );
}

/// Append the HTML provenance footer: a `<footer class="provenance">` block
/// with the same sentence, escaped for HTML. The whole sentence is escaped
/// once, so `paths` passes through unescaped here and is neutralized by the
/// outer `escape_html`.
pub(crate) fn push_html_footer(out: &mut String, prov: &Provenance<'_>) {
    let _ = writeln!(
        out,
        "<footer class=\"provenance\"><p>{}</p></footer>",
        escape_html(&prov.sentence(str::to_owned))
    );
}

/// Resolve the generation date as `YYYY-MM-DD` (UTC). Honors
/// `SOURCE_DATE_EPOCH` (a Unix timestamp in seconds) when set and parseable
/// — the reproducible-builds standard — otherwise the system wall clock. A
/// malformed `SOURCE_DATE_EPOCH` falls back to the wall clock rather than
/// failing the report.
pub(crate) fn resolved_date() -> String {
    let secs = std::env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|s| s.trim().parse::<i64>().ok())
        .unwrap_or_else(wall_clock_secs);
    format_civil_date(secs)
}

/// Seconds since the Unix epoch from the system clock, or `0` if the clock is
/// before the epoch (which would only happen on a badly misconfigured host).
fn wall_clock_secs() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_secs() as i64)
}

/// Convert a Unix timestamp (seconds, UTC) to a `YYYY-MM-DD` civil date via
/// Howard Hinnant's `days_from_civil` inverse (`civil_from_days`), so no date
/// crate is needed for a once-per-report stamp.
fn format_civil_date(secs: i64) -> String {
    // Days since 1970-01-01, flooring toward negative infinity for pre-epoch
    // inputs (only reachable via a hand-set SOURCE_DATE_EPOCH).
    const SECS_PER_DAY: i64 = 86_400;
    let days = secs.div_euclid(SECS_PER_DAY);
    let (y, m, d) = civil_from_days(days);
    format!("{y:04}-{m:02}-{d:02}")
}

/// Howard Hinnant's `civil_from_days`: the calendar date `(year, month, day)`
/// for a count of days since 1970-01-01. Public-domain algorithm, valid for
/// the full range of dates a report will ever stamp.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as i64; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    (if m <= 2 { y + 1 } else { y }, m, d)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn prov<'a>(top: usize, policy: SuppressionPolicy) -> Provenance<'a> {
        Provenance {
            version: "9.9.9",
            date: "2026-06-11",
            paths: "src/",
            top,
            policy,
        }
    }

    #[test]
    fn markdown_footer_states_every_field() {
        let mut out = String::new();
        push_markdown_footer(&mut out, &prov(20, SuppressionPolicy::Honor));
        // The seed path is wrapped in a backtick code span (issue #848) so the
        // static prefix and the path render separately.
        assert!(out.contains("Generated by bca 9.9.9 on 2026-06-11 over `src/`"));
        assert!(out.contains("top 20 per table"));
        assert!(out.contains("suppression markers honored."));
        // Footnote separator.
        assert!(out.contains("\n---\n"));
    }

    #[test]
    fn footer_reflects_no_suppress_and_show_all() {
        let mut out = String::new();
        push_markdown_footer(&mut out, &prov(0, SuppressionPolicy::Ignore));
        assert!(out.contains("all entries per table"));
        assert!(out.contains("suppression markers ignored."));
    }

    #[test]
    fn markdown_footer_escapes_active_chars_in_seed_paths() {
        // A path with Markdown-active characters (`_`, `*`, `` ` ``) must not
        // leak into the surrounding `_..._` emphasis span (issue #848).
        let mut out = String::new();
        let p = Provenance {
            paths: "__tests__/a*b",
            ..prov(20, SuppressionPolicy::Honor)
        };
        push_markdown_footer(&mut out, &p);
        // The path is wrapped in a backtick code span, so its `_`/`*` are
        // inert and the only emphasis delimiters are the footer's own
        // leading/trailing `_`.
        assert!(
            out.contains("over `__tests__/a*b`"),
            "seed path must be backtick-wrapped, got: {out}"
        );
        // No bare `__tests__` (which would open bold), i.e. the path's
        // underscores are inside the span, not loose in the sentence.
        assert!(
            !out.contains(" __tests__"),
            "path underscores must be neutralized, got: {out}"
        );
    }

    #[test]
    fn html_footer_escapes_and_wraps() {
        let mut out = String::new();
        let p = Provenance {
            paths: "src/<a>",
            ..prov(20, SuppressionPolicy::Honor)
        };
        push_html_footer(&mut out, &p);
        assert!(out.contains("<footer class=\"provenance\">"));
        assert!(out.contains("src/&lt;a&gt;"), "paths must be HTML-escaped");
    }

    #[test]
    fn source_date_epoch_pins_the_date() {
        // 1_700_000_000 = 2023-11-14T22:13:20Z -> civil date 2023-11-14.
        assert_eq!(format_civil_date(1_700_000_000), "2023-11-14");
        // Epoch itself.
        assert_eq!(format_civil_date(0), "1970-01-01");
        // A known leap day.
        assert_eq!(format_civil_date(1_582_934_400), "2020-02-29");
    }

    #[test]
    fn resolved_date_is_well_formed() {
        // Avoid mutating the shared process env from a parallel test; the
        // SOURCE_DATE_EPOCH parsing path is covered by `format_civil_date`
        // above. Here just confirm the resolved date is a `YYYY-MM-DD` string.
        let date = resolved_date();
        let parts: Vec<&str> = date.split('-').collect();
        assert_eq!(parts.len(), 3, "date must be YYYY-MM-DD, got {date}");
        assert_eq!(parts[0].len(), 4);
        assert!(parts.iter().all(|p| p.chars().all(|c| c.is_ascii_digit())));
    }
}
