// @generated by big-code-analysis test fixture. DO NOT EDIT.
//
// Combined-kwarg fixture: the leading marker triggers `is_generated`
// so `skip_generated=True` returns `None`, while the `#[test]`
// subtree below exercises `exclude_tests=True` pruning when the
// caller opts back into parsing with `skip_generated=False`.
fn prod(x: i32) -> i32 {
    if x > 0 { x + 1 } else { -x }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn helper() -> i32 {
        42
    }

    #[test]
    fn checks_positive() {
        assert_eq!(prod(1), 2);
        assert_eq!(helper(), 42);
    }
}
