// @generated by big-code-analysis test fixture. DO NOT EDIT.
//
// Marker on line 1 triggers `big_code_analysis::is_generated` so the
// CLI walker and the bindings (when `skip_generated=True`) both
// discard this file before parsing.
pub fn generated() -> i32 {
    if true { 1 } else { 2 }
}
