# @generated by `big-code-analysis-py` from the live `LANG` / `Metric`
# tables — DO NOT EDIT BY HAND. Regenerate with:
#
#     BCA_PY_REGEN_ENUMS=1 cargo test -p big-code-analysis-py enums_module
#
# The values are the canonical CLI/JSON language slugs (`LANG::name()`,
# #540) and the metric vocabulary (`Metric::NAMES`). `StrEnum` members
# compare equal to their string value (`Lang.CPP == "cpp"`), so they
# round-trip with `analyze_source`, `language_extensions`, and the
# `metrics=` selector.
"""Generated string enums for languages and metric names."""

from __future__ import annotations

from enum import StrEnum

__all__ = ["Lang", "MetricName"]


class Lang(StrEnum):
    """A supported source language; its value is the canonical slug."""

    JAVASCRIPT = "javascript"
    MOZJS = "mozjs"
    JAVA = "java"
    GO = "go"
    KOTLIN = "kotlin"
    LUA = "lua"
    RUST = "rust"
    TCL = "tcl"
    IRULES = "irules"
    C = "c"
    CPP = "cpp"
    MOZCPP = "mozcpp"
    CSHARP = "csharp"
    ELIXIR = "elixir"
    PYTHON = "python"
    TSX = "tsx"
    TYPESCRIPT = "typescript"
    BASH = "bash"
    PERL = "perl"
    PHP = "php"
    RUBY = "ruby"
    GROOVY = "groovy"


class MetricName(StrEnum):
    """A computable metric; its value matches `bca.METRIC_NAMES`."""

    ABC = "abc"
    COGNITIVE = "cognitive"
    CYCLOMATIC = "cyclomatic"
    HALSTEAD = "halstead"
    LOC = "loc"
    MI = "mi"
    NARGS = "nargs"
    NEXITS = "nexits"
    NOM = "nom"
    NPA = "npa"
    NPM = "npm"
    TOKENS = "tokens"
    WMC = "wmc"
