# @generated by `big-code-analysis-py` from the `big_code_analysis::wire`
# shapes (src/wire.rs) — DO NOT EDIT BY HAND. Regenerate with:
#
#     BCA_PY_REGEN_TYPES=1 cargo test -p big-code-analysis-py types_module
#
# These TypedDicts mirror the JSON projection that `analyze` /
# `analyze_source` / `analyze_batch` return. They are stub-only: the
# runtime values are plain dicts, byte-identical to the CLI's JSON, so a
# TypedDict annotation only narrows the static type. `total=False` blocks
# (CodeMetricsDict) and NotRequired fields cover keys elided under
# `metrics=` selection or when no suppression marker fired.
"""Generated TypedDicts for the analysis-result wire shapes (#623)."""

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

__all__ = [
    "AbcDict",
    "BusFactorDict",
    "CodeMetricsDict",
    "CognitiveDict",
    "CyclomaticDict",
    "CyclomaticModifiedDict",
    "DirectoryBusFactorDict",
    "FuncSpaceDict",
    "GroupBusFactorDict",
    "HalsteadDict",
    "JitCommitDict",
    "JitCommitReportDict",
    "JitContributionsDict",
    "JitDiffContributionsDict",
    "JitDiffReportDict",
    "JitDiffusionDict",
    "JitExperienceDict",
    "JitFeaturesDict",
    "JitHistoryDict",
    "JitPurposeDict",
    "JitSizeDict",
    "LocDict",
    "MiDict",
    "NargsDict",
    "NexitsDict",
    "NomDict",
    "NpaDict",
    "NpmDict",
    "SuppressionScopeDict",
    "TokensDict",
    "VcsAggregateDict",
    "VcsDict",
    "VcsReportDict",
    "VcsReportFileDict",
    "VcsTrendDeltaDict",
    "VcsTrendDeltasDict",
    "VcsTrendDict",
    "VcsTrendPointDict",
    "WmcDict",
]


class SuppressionScopeDict(TypedDict):
    """In-source suppression scope (`bca:`/Lizard markers). `kind` is `"all"` (suppress every
    metric) or `"some"` (only the listed `metrics`, present only then).
    """

    kind: str
    metrics: NotRequired[list[str]]


class AbcDict(TypedDict):
    """ABC metric block (assignments / branches / conditions)."""

    assignments: int
    branches: int
    conditions: int
    magnitude: float | None
    assignments_average: float | None
    branches_average: float | None
    conditions_average: float | None
    assignments_min: int
    assignments_max: int
    branches_min: int
    branches_max: int
    conditions_min: int
    conditions_max: int


class CognitiveDict(TypedDict):
    """Cognitive-complexity metric block."""

    sum: int
    average: float | None
    min: int
    max: int


class CyclomaticModifiedDict(TypedDict):
    """Modified-cyclomatic sub-block of `CyclomaticDict`."""

    sum: int
    average: float | None
    min: int
    max: int


class CyclomaticDict(TypedDict):
    """Cyclomatic-complexity metric block."""

    sum: int
    average: float | None
    min: int
    max: int
    modified: CyclomaticModifiedDict


class NexitsDict(TypedDict):
    """Exit-points (`nexits`) metric block."""

    sum: int
    average: float | None
    min: int
    max: int


class HalsteadDict(TypedDict):
    """Halstead metric suite."""

    unique_operators: int
    total_operators: int
    unique_operands: int
    total_operands: int
    length: int
    estimated_program_length: float | None
    purity_ratio: float | None
    vocabulary: int
    volume: float | None
    difficulty: float | None
    level: float | None
    effort: float | None
    time: float | None
    bugs: float | None


class LocDict(TypedDict):
    """Lines-of-code metric suite."""

    sloc: int
    ploc: int
    lloc: int
    cloc: int
    blank: int
    sloc_average: float | None
    ploc_average: float | None
    lloc_average: float | None
    cloc_average: float | None
    blank_average: float | None
    sloc_min: int
    sloc_max: int
    cloc_min: int
    cloc_max: int
    ploc_min: int
    ploc_max: int
    lloc_min: int
    lloc_max: int
    blank_min: int
    blank_max: int


class MiDict(TypedDict):
    """Maintainability-index metric block."""

    original: float | None
    sei: float | None
    visual_studio: float | None


class NargsDict(TypedDict):
    """Number-of-arguments metric block."""

    function_args: int
    closure_args: int
    function_args_average: float | None
    closure_args_average: float | None
    total: int
    average: float | None
    function_args_min: int
    function_args_max: int
    closure_args_min: int
    closure_args_max: int


class NomDict(TypedDict):
    """Number-of-methods metric block."""

    functions: int
    closures: int
    functions_average: float | None
    closures_average: float | None
    total: int
    average: float | None
    functions_min: int
    functions_max: int
    closures_min: int
    closures_max: int


class NpaDict(TypedDict):
    """Number-of-public-attributes metric block."""

    class_npa_sum: int
    interface_npa_sum: int
    class_attributes: int
    interface_attributes: int
    class_cda: float | None
    interface_cda: float | None
    total: int
    total_attributes: int
    cda: float | None


class NpmDict(TypedDict):
    """Number-of-public-methods metric block."""

    class_npm_sum: int
    interface_npm_sum: int
    class_methods: int
    interface_methods: int
    class_coa: float | None
    interface_coa: float | None
    total: int
    total_methods: int
    coa: float | None


class TokensDict(TypedDict):
    """Token-count metric block."""

    tokens: int
    average: float | None
    min: int
    max: int


class WmcDict(TypedDict):
    """Weighted-methods-per-class metric block."""

    class_wmc_sum: int
    interface_wmc_sum: int
    total: int


class VcsDict(TypedDict):
    """Change-history (VCS) metric block; present only under `vcs=True` / `vcs_per_function=True`.
    Always-slim (issue #635): the constant `*_version` / `*_window_days` stamps live once on the
    `vcs.rank` / `vcs.trend` envelope, not on each block. `hotspot_score` and `author_ids` are
    elided when unavailable.
    """

    commits_long: int
    commits_recent: int
    churn_long: int
    churn_recent: int
    authors_long: int
    authors_recent: int
    ownership_top_share: float | None
    burst: float | None
    bug_fix_commits: int
    security_fix_commits: int
    revert_commits: int
    age_days: int
    last_modified_days: int
    change_entropy_long: float | None
    change_entropy_recent: float | None
    cochange_entropy_long: float | None
    cochange_entropy_recent: float | None
    risk_score: float | None
    hotspot_score: NotRequired[float | None]
    author_ids: NotRequired[list[str]]


class GroupBusFactorDict(TypedDict):
    """Bus-factor numbers for one author group (the repo, or one directory). `key_author_ids` is
    present only under `emit_author_details=True`.
    """

    bus_factor: int
    files: int
    authors: int
    key_author_ids: NotRequired[list[str]]


class DirectoryBusFactorDict(TypedDict):
    """Per-directory bus factor: a directory path plus its `GroupBusFactorDict` fields (flattened
    inline in the wire shape).
    """

    directory: str
    bus_factor: int
    files: int
    authors: int
    key_author_ids: NotRequired[list[str]]


class BusFactorDict(TypedDict):
    """Directory-/repo-level bus-factor aggregate (Avelino DoA, issue #332)."""

    bus_factor_schema_version: int
    coverage_threshold: float | None
    doa_threshold: float | None
    repo: GroupBusFactorDict
    by_directory: list[DirectoryBusFactorDict]


class VcsAggregateDict(TypedDict):
    """Top-level change-history aggregate object wrapping the bus-factor summary."""

    bus_factor: BusFactorDict


class VcsReportFileDict(TypedDict):
    """One ranked file in a `VcsReportDict`: its repository-relative path plus the always-slim
    `vcs` block (issue #684).
    """

    path: str
    vcs: VcsDict


class VcsReportDict(TypedDict):
    """Return type of `big_code_analysis.vcs.rank()` — the file-ranking change-history report
    (issue #328 / #664). The four constant stamps sit once at the top level (issue #635);
    `files` is ranked by descending `vcs.risk_score`. `vcs_aggregate` is present only when the
    bus factor was computed.
    """

    long_window_days: int
    recent_window_days: int
    risk_score_version: int
    vcs_schema_version: int
    truncated_shallow_clone: bool
    vcs_aggregate: NotRequired[VcsAggregateDict]
    files: list[VcsReportFileDict]


class VcsTrendPointDict(TypedDict):
    """One sampled point in a `VcsTrendDict`: the sample timestamp plus the file's `vcs` block at
    that moment (issue #333 / #684).
    """

    as_of: int
    vcs: VcsDict


class VcsTrendDeltaDict(TypedDict):
    """One file's risk-score movement across the trend."""

    path: str
    first_as_of: int
    last_as_of: int
    first_risk_score: float | None
    last_risk_score: float | None
    delta: float | None


class VcsTrendDeltasDict(TypedDict):
    """The improving / regressing delta summary."""

    improved: list[VcsTrendDeltaDict]
    regressed: list[VcsTrendDeltaDict]


class VcsTrendDict(TypedDict):
    """Return type of `big_code_analysis.vcs.trend()` — a historical metric trend (issue #333 /
    #664). `as_of_points` lists the sample timestamps oldest-first; every file's series in
    `files` aligns to it 1:1, with a `None` element where the file did not exist.
    """

    trend_schema_version: int
    vcs_schema_version: int
    risk_score_version: int
    long_window_days: int
    recent_window_days: int
    truncated_shallow_clone: bool
    as_of_points: list[int]
    files: dict[str, list[VcsTrendPointDict | None]]
    deltas: VcsTrendDeltasDict


class JitSizeDict(TypedDict):
    """Commit / diff size features."""

    lines_added: int
    lines_deleted: int
    files_touched: int
    hunks: int


class JitDiffusionDict(TypedDict):
    """Change-diffusion features (subsystem / directory spread)."""

    subsystems: int
    directories: int
    entropy: float | None


class JitHistoryDict(TypedDict):
    """Prior-change history features (commit mode only)."""

    prior_changes: int
    prior_distinct_authors: int
    prior_bug_fix_commits: int
    prior_security_fix_commits: int
    file_risk_max: float | None
    file_risk_mean: float | None
    new_files: int


class JitExperienceDict(TypedDict):
    """Author-experience features (commit mode only)."""

    author_prior_commits: int
    author_recent_commits: int


class JitPurposeDict(TypedDict):
    """Commit-purpose flags derived from the message."""

    is_fix: bool
    is_security_fix: bool
    is_revert: bool


class JitFeaturesDict(TypedDict):
    """The four feature groups computed for a commit score."""

    size: JitSizeDict
    diffusion: JitDiffusionDict
    history: JitHistoryDict
    experience: JitExperienceDict


class JitContributionsDict(TypedDict):
    """Per-group contributions to a commit `risk_score`."""

    size: float | None
    diffusion: float | None
    history: float | None
    purpose: float | None
    experience: float | None


class JitCommitDict(TypedDict):
    """The scored commit's identity and purpose flags."""

    id: str
    parent_count: int
    is_merge: bool
    purpose: JitPurposeDict


class JitCommitReportDict(TypedDict):
    """Return type of `big_code_analysis.vcs.commit()` — the commit just-in-time risk report
    (issue #331 / #664). `source` is the literal `"commit"`; all five feature groups are present
    and `risk_score` is comparable across commits.
    """

    jit_schema_version: int
    jit_score_version: int
    source: Literal["commit"]
    long_window_days: int
    recent_window_days: int
    risk_score: float | None
    commit: JitCommitDict
    features: JitFeaturesDict
    contributions: JitContributionsDict


class JitDiffContributionsDict(TypedDict):
    """Per-group contributions to a diff `partial_risk_score` (only size + diffusion are computable
    for a bare diff).
    """

    size: float | None
    diffusion: float | None


class JitDiffReportDict(TypedDict):
    """Return type of `big_code_analysis.vcs.score_diff()` — the partial just-in-time risk report
    for a bare diff (issue #580 / #664). `source` is the literal `"diff"`; only size and
    diffusion are computable, so `partial_risk_score` is **not comparable** to a commit
    `risk_score` and the history / experience / purpose groups are absent.
    """

    jit_schema_version: int
    jit_score_version: int
    source: Literal["diff"]
    partial_risk_score: float | None
    size: JitSizeDict
    diffusion: JitDiffusionDict
    contributions: JitDiffContributionsDict


class CodeMetricsDict(TypedDict, total=False):
    """Per-space metric table. Every block is `NotRequired`: a `metrics=` selection (or a
    class-only metric on a non-class language) elides the unselected blocks entirely.
    """

    nargs: NargsDict
    nexits: NexitsDict
    cognitive: CognitiveDict
    cyclomatic: CyclomaticDict
    halstead: HalsteadDict
    loc: LocDict
    nom: NomDict
    tokens: TokensDict
    mi: MiDict
    abc: AbcDict
    wmc: WmcDict
    npm: NpmDict
    npa: NpaDict
    vcs: VcsDict


class FuncSpaceDict(TypedDict):
    """A metric space: the file-level `unit` space or a nested function / class / impl. Returned by
    `analyze`, `analyze_source`, and the dict entries of `analyze_batch`.
    """

    name: str | None
    start_line: int
    end_line: int
    kind: str
    spaces: list[FuncSpaceDict]
    metrics: CodeMetricsDict
    suppressed: NotRequired[SuppressionScopeDict]
