# @generated by `big-code-analysis-py` from the `big_code_analysis::wire`
# shapes (src/wire.rs) — DO NOT EDIT BY HAND. Regenerate with:
#
#     BCA_PY_REGEN_TYPES=1 cargo test -p big-code-analysis-py types_module
#
# These TypedDicts mirror the JSON projection that `analyze` /
# `analyze_source` / `analyze_batch` return. They are stub-only: the
# runtime values are plain dicts, byte-identical to the CLI's JSON, so a
# TypedDict annotation only narrows the static type. `total=False` blocks
# (CodeMetricsDict) and NotRequired fields cover keys elided under
# `metrics=` selection or when no suppression marker fired.
"""Generated TypedDicts for the analysis-result wire shapes (#623)."""

from __future__ import annotations

from typing import NotRequired, TypedDict

__all__ = [
    "AbcDict",
    "CodeMetricsDict",
    "CognitiveDict",
    "CyclomaticDict",
    "CyclomaticModifiedDict",
    "FuncSpaceDict",
    "HalsteadDict",
    "LocDict",
    "MiDict",
    "NargsDict",
    "NexitsDict",
    "NomDict",
    "NpaDict",
    "NpmDict",
    "SuppressionScopeDict",
    "TokensDict",
    "VcsDict",
    "WmcDict",
]


class SuppressionScopeDict(TypedDict):
    """In-source suppression scope (`bca:`/Lizard markers). `kind` is `"all"` (suppress every
    metric) or `"some"` (only the listed `metrics`, present only then).
    """

    kind: str
    metrics: NotRequired[list[str]]


class AbcDict(TypedDict):
    """ABC metric block (assignments / branches / conditions)."""

    assignments: int
    branches: int
    conditions: int
    magnitude: float | None
    assignments_average: float | None
    branches_average: float | None
    conditions_average: float | None
    assignments_min: int
    assignments_max: int
    branches_min: int
    branches_max: int
    conditions_min: int
    conditions_max: int


class CognitiveDict(TypedDict):
    """Cognitive-complexity metric block."""

    sum: int
    average: float | None
    min: int
    max: int


class CyclomaticModifiedDict(TypedDict):
    """Modified-cyclomatic sub-block of `CyclomaticDict`."""

    sum: int
    average: float | None
    min: int
    max: int


class CyclomaticDict(TypedDict):
    """Cyclomatic-complexity metric block."""

    sum: int
    average: float | None
    min: int
    max: int
    modified: CyclomaticModifiedDict


class NexitsDict(TypedDict):
    """Exit-points (`nexits`) metric block."""

    sum: int
    average: float | None
    min: int
    max: int


class HalsteadDict(TypedDict):
    """Halstead metric suite."""

    unique_operators: int
    total_operators: int
    unique_operands: int
    total_operands: int
    length: int
    estimated_program_length: float | None
    purity_ratio: float | None
    vocabulary: int
    volume: float | None
    difficulty: float | None
    level: float | None
    effort: float | None
    time: float | None
    bugs: float | None


class LocDict(TypedDict):
    """Lines-of-code metric suite."""

    sloc: int
    ploc: int
    lloc: int
    cloc: int
    blank: int
    sloc_average: float | None
    ploc_average: float | None
    lloc_average: float | None
    cloc_average: float | None
    blank_average: float | None
    sloc_min: int
    sloc_max: int
    cloc_min: int
    cloc_max: int
    ploc_min: int
    ploc_max: int
    lloc_min: int
    lloc_max: int
    blank_min: int
    blank_max: int


class MiDict(TypedDict):
    """Maintainability-index metric block."""

    original: float | None
    sei: float | None
    visual_studio: float | None


class NargsDict(TypedDict):
    """Number-of-arguments metric block."""

    function_args: int
    closure_args: int
    function_args_average: float | None
    closure_args_average: float | None
    total: int
    average: float | None
    function_args_min: int
    function_args_max: int
    closure_args_min: int
    closure_args_max: int


class NomDict(TypedDict):
    """Number-of-methods metric block."""

    functions: int
    closures: int
    functions_average: float | None
    closures_average: float | None
    total: int
    average: float | None
    functions_min: int
    functions_max: int
    closures_min: int
    closures_max: int


class NpaDict(TypedDict):
    """Number-of-public-attributes metric block."""

    classes: int
    interfaces: int
    class_attributes: int
    interface_attributes: int
    class_cda: float | None
    interface_cda: float | None
    total: int
    total_attributes: int
    cda: float | None


class NpmDict(TypedDict):
    """Number-of-public-methods metric block."""

    classes: int
    interfaces: int
    class_methods: int
    interface_methods: int
    class_coa: float | None
    interface_coa: float | None
    total: int
    total_methods: int
    coa: float | None


class TokensDict(TypedDict):
    """Token-count metric block."""

    tokens: int
    tokens_average: float | None
    tokens_min: int
    tokens_max: int


class WmcDict(TypedDict):
    """Weighted-methods-per-class metric block."""

    classes: int
    interfaces: int
    total: int


class VcsDict(TypedDict):
    """Change-history (VCS) metric block; present only under `vcs=True` / `vcs_per_function=True`.
    `hotspot_score` and `author_ids` are elided when unavailable.
    """

    vcs_schema_version: int
    risk_score_version: int
    long_window_days: int
    recent_window_days: int
    commits_long: int
    commits_recent: int
    churn_long: int
    churn_recent: int
    authors_long: int
    authors_recent: int
    ownership_top_share: float | None
    burst: float | None
    bug_fix_commits: int
    security_fix_commits: int
    revert_commits: int
    age_days: int
    last_modified_days: int
    change_entropy_long: float | None
    change_entropy_recent: float | None
    cochange_entropy_long: float | None
    cochange_entropy_recent: float | None
    risk_score: float | None
    hotspot_score: NotRequired[float | None]
    author_ids: NotRequired[list[str]]


class CodeMetricsDict(TypedDict, total=False):
    """Per-space metric table. Every block is `NotRequired`: a `metrics=` selection (or a
    class-only metric on a non-class language) elides the unselected blocks entirely.
    """

    nargs: NargsDict
    nexits: NexitsDict
    cognitive: CognitiveDict
    cyclomatic: CyclomaticDict
    halstead: HalsteadDict
    loc: LocDict
    nom: NomDict
    tokens: TokensDict
    mi: MiDict
    abc: AbcDict
    wmc: WmcDict
    npm: NpmDict
    npa: NpaDict
    vcs: VcsDict


class FuncSpaceDict(TypedDict):
    """A metric space: the file-level `unit` space or a nested function / class / impl. Returned by
    `analyze`, `analyze_source`, and the dict entries of `analyze_batch`.
    """

    name: str | None
    start_line: int
    end_line: int
    kind: str
    spaces: list[FuncSpaceDict]
    metrics: CodeMetricsDict
    suppressed: NotRequired[SuppressionScopeDict]
