//! Deterministic generator for the checked-in `_enums.py` module.
//!
//! The `Lang` and `MetricName` `StrEnum`s exposed to Python are
//! generated from the **live** upstream tables — `LANG::name()` (the
//! #540 canonical language slugs) and [`Metric::NAMES`] (the metric
//! vocabulary) — so the Python enum values cannot drift from the CLI /
//! JSON slugs. The generated file is checked in (IDEs, `mypy`, and
//! `pyright` all need a static `.py` to resolve `Lang.CPP`), and the
//! `enums_module_matches_checked_in` test in `tests` acts as the
//! drift gate: regenerate with `BCA_PY_REGEN_ENUMS=1 cargo test -p
//! big-code-analysis-py enums_module` after a `LANG`/`Metric` change.
//!
//! This lives in the bindings crate rather than the workspace-excluded
//! `enums/` helper deliberately: `enums/` carries its own
//! hand-maintained `Lang` list with CamelCase names and does not
//! depend on `big-code-analysis`, so it cannot see the #540 slugs.
//! Sourcing the enum here, where the crate already depends on the
//! library, keeps the single source of truth on `LANG::name()`.

use std::fmt::Write as _;

use big_code_analysis::{LANG, Metric};

/// Path of the generated module relative to the crate root.
pub(crate) const ENUMS_MODULE_PATH: &str = "python/big_code_analysis/_enums.py";

/// Language slugs exposed to Python, in `LANG` declaration order.
///
/// Mirrors [`crate::language::supported_languages`]: only variants
/// with at least one registered file extension are public (the
/// `Ccomment` / `Preproc` helpers are filtered out), so every member
/// round-trips through `analyze_source` and `language_extensions`.
fn language_slugs() -> Vec<&'static str> {
    // Single-source the public-language predicate with the runtime
    // `supported_languages()` set (`language::is_public_language`) so the
    // generated `Lang` enum cannot drift from it. Extension-less but
    // public languages — the opt-in `Mozcpp` dialect since #720 — are
    // included; only the internal `Ccomment` / `Preproc` helpers are not.
    LANG::into_enum_iter()
        .filter(|&lang| crate::language::is_public_language(lang))
        .map(|lang| lang.name())
        .collect()
}

/// Render a single `StrEnum` class body from a list of string values.
///
/// The member identifier is the value upper-cased; every current slug
/// and metric name is a simple lowercase ASCII identifier, so the
/// upper-casing is a total, collision-free mapping. The guard rejects
/// any future value that would not yield a valid Python identifier
/// rather than emit a syntactically broken module.
fn render_enum(class: &str, doc: &str, values: &[&str]) -> Result<String, String> {
    let mut out = format!("class {class}(StrEnum):\n    \"\"\"{doc}\"\"\"\n\n");
    for value in values {
        let member = value.to_uppercase();
        if member.is_empty()
            || !member
                .chars()
                .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
            || member.chars().next().is_some_and(|c| c.is_ascii_digit())
        {
            return Err(format!(
                "value {value:?} does not map to a valid Python identifier \
                 ({member:?}); extend render_enum to handle it"
            ));
        }
        // `writeln!` into a `String` is infallible; the `Write` impl
        // never returns `Err`, so the result is intentionally ignored.
        let _ = writeln!(out, "    {member} = \"{value}\"");
    }
    Ok(out)
}

/// Render the full `_enums.py` module text.
///
/// Output is deterministic (declaration order, no timestamps) so the
/// drift-gate test can byte-compare it against the checked-in file.
pub(crate) fn render_enums_module() -> Result<String, String> {
    let header = "\
# @generated by `big-code-analysis-py` from the live `LANG` / `Metric`
# tables — DO NOT EDIT BY HAND. Regenerate with:
#
#     BCA_PY_REGEN_ENUMS=1 cargo test -p big-code-analysis-py enums_module
#
# The values are the canonical CLI/JSON language slugs (`LANG::name()`,
# #540) and the metric vocabulary (`Metric::NAMES`). `StrEnum` members
# compare equal to their string value (`Lang.CPP == \"cpp\"`), so they
# round-trip with `analyze_source`, `language_extensions`, and the
# `metrics=` selector.
\"\"\"Generated string enums for languages and metric names.\"\"\"

from __future__ import annotations

from enum import StrEnum

__all__ = [\"Lang\", \"MetricName\"]


";

    let lang = render_enum(
        "Lang",
        "A supported source language; its value is the canonical slug.",
        &language_slugs(),
    )?;
    let metric = render_enum(
        "MetricName",
        "A computable metric; its value matches `bca.METRIC_NAMES`.",
        Metric::NAMES,
    )?;

    Ok(format!("{header}{lang}\n\n{metric}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// Drift gate: the checked-in `_enums.py` must match the module
    /// rendered from the live `LANG` / `Metric` tables. A `LANG`
    /// rename, a new language, or a metric-vocabulary change moves
    /// the rendered text; regenerate by setting `BCA_PY_REGEN_ENUMS=1`
    /// when running this test, then commit the updated file.
    #[test]
    fn enums_module_matches_checked_in() {
        let rendered = render_enums_module().expect("render _enums.py");
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(ENUMS_MODULE_PATH);

        if std::env::var_os("BCA_PY_REGEN_ENUMS").is_some() {
            std::fs::write(&path, &rendered).expect("write _enums.py");
            return;
        }

        let checked_in = std::fs::read_to_string(&path).expect("read _enums.py");
        assert_eq!(
            checked_in, rendered,
            "{ENUMS_MODULE_PATH} drifted from the live LANG/Metric tables; \
             regenerate with `BCA_PY_REGEN_ENUMS=1 cargo test -p \
             big-code-analysis-py enums_module`",
        );
    }

    /// The `Lang` values must be exactly the public language slugs
    /// `supported_languages()` exposes — the whole point of #540 is
    /// that the Python enum, the CLI, and the JSON `language` field
    /// agree on one slug per language.
    #[test]
    fn lang_slugs_match_supported_languages() {
        assert_eq!(language_slugs(), crate::language::supported_languages());
    }

    /// Guard the identifier mapping: every value in scope must yield a
    /// distinct, valid Python member name. Reuses the production
    /// renderer so a future slug like `"c++"` fails the gate here
    /// rather than emitting a broken module.
    #[test]
    fn render_enum_rejects_non_identifier_values() {
        assert!(render_enum("Bad", "doc", &["c++"]).is_err());
        assert!(render_enum("Bad", "doc", &["1bad"]).is_err());
        assert!(render_enum("Ok", "doc", &["cpp", "csharp"]).is_ok());
    }
}
