//! Language detection helpers exposed to Python.
//!
//! These thin wrappers reuse the upstream `LANG` enum and its
//! [`big_code_analysis::get_language_for_file`] helper directly for
//! extension matching — the inverse-lookup table cannot drift between
//! Rust and Python because both call the same macro-generated
//! `get_from_ext`. The *forward* lookup (variant → name) is owned by
//! [`lang_to_name`] in this module: the upstream `LANG::get_name`
//! returns a display string shared across variants (both `Tsx` and
//! `Typescript` report `"typescript"`), so the Python facade carries
//! its own variant-keyed name table to keep the two disambiguated.

use std::path::Path;

use big_code_analysis::{LANG, get_language_for_file};

/// Returns the Python-facing language identifier for `lang`.
///
/// The upstream `LANG::get_name` returns a *display* name shared
/// across variants — both `LANG::Tsx` and `LANG::Typescript` report
/// `"typescript"`, both `LANG::Mozjs` and `LANG::Javascript` report
/// `"javascript"` — which makes it ambiguous as a *lookup* key when
/// two variants would round-trip differently through
/// `parse_language_name`. The Python bindings disambiguate by
/// preferring the upstream display name when only one variant in a
/// display group is actually reachable (no helper-variant collision),
/// and falling back to the lowercase Rust variant name otherwise:
///
/// - `Mozjs` is exposed as `"javascript"` — matches the CLI's
///   `"language"` field on every `.js` / `.jsm` / `.mjs` / `.jsx`
///   file. `LANG::Javascript` exists as a placeholder for a future
///   strict-ECMAScript dispatch but has no registered extensions
///   and is filtered out by [`public_languages`], so the shared
///   `"javascript"` name is unambiguous from the Python API.
/// - `Tsx` and `Typescript` get distinct variant names (`"tsx"`,
///   `"typescript"`) because both are reachable (TSX via `.tsx`
///   files, TypeScript via `.ts`) and the CLI display collision
///   would lose information at the API boundary.
/// - `Csharp` is exposed as `"csharp"`.
/// - All other variants use their variant name lowercased
///   (`Rust` → `"rust"`, `Java` → `"java"`, …).
pub(crate) fn lang_to_name(lang: LANG) -> &'static str {
    match lang {
        LANG::Bash => "bash",
        LANG::Ccomment => "ccomment",
        LANG::Cpp => "cpp",
        LANG::Csharp => "csharp",
        LANG::Elixir => "elixir",
        LANG::Go => "go",
        LANG::Groovy => "groovy",
        LANG::Java => "java",
        // `Javascript` has no extensions and is filtered out of
        // `public_languages`, so this arm is never reached through
        // the Python API — but the match must stay exhaustive, and
        // grouping the two `"javascript"` variants together documents
        // the intentional CLI-name alias and keeps clippy
        // (`match_same_arms`) quiet.
        LANG::Javascript | LANG::Mozjs => "javascript",
        LANG::Kotlin => "kotlin",
        LANG::Lua => "lua",
        LANG::Perl => "perl",
        LANG::Php => "php",
        LANG::Preproc => "preproc",
        LANG::Python => "python",
        LANG::Ruby => "ruby",
        LANG::Rust => "rust",
        LANG::Tcl => "tcl",
        LANG::Tsx => "tsx",
        LANG::Typescript => "typescript",
    }
}

/// Returns the language name (as accepted by `analyze_source`) that
/// matches `path`'s file extension, or `None` when the extension is
/// not recognised.
///
/// Mirrors [`big_code_analysis::get_language_for_file`] one-to-one —
/// agreement with the Rust side is guaranteed because both call into
/// the same `get_from_ext` table generated by `mk_extensions!`.
pub(crate) fn language_for_file(path: &Path) -> Option<&'static str> {
    get_language_for_file(path).map(lang_to_name)
}

/// Iterator over the `LANG` variants exposed to Python.
///
/// "Public" means the variant has at least one registered file
/// extension — internal helper variants without user-facing files
/// (`Ccomment`, `Preproc`) are filtered out, since the Python
/// facade has no way to feed them a file and exposing them on the
/// `language` argument would let callers route arbitrary source
/// through the C-preprocessing pipeline.
fn public_languages() -> impl Iterator<Item = LANG> {
    LANG::into_enum_iter().filter(|lang| !lang.get_extensions().is_empty())
}

/// Returns the supported language names, in declaration order.
///
/// "Supported" here means the variant exists in the `LANG` enum and
/// has at least one registered file extension. Every variant is
/// always present regardless of the Cargo feature set, so this list
/// does not depend on which grammars were compiled in. Internal
/// helper variants without user-facing files (`Ccomment`, `Preproc`)
/// are filtered out because they cannot be reached through any
/// extension table and accept no user input.
pub(crate) fn supported_languages() -> Vec<&'static str> {
    public_languages().map(lang_to_name).collect()
}

/// Returns the file extensions that resolve to `name`, or `None` when
/// `name` is not a recognised language.
///
/// The list is the same one consulted by `get_from_ext` and
/// `get_language_for_file` for the matching variant — every extension
/// here will round-trip through [`language_for_file`].
pub(crate) fn language_extensions(name: &str) -> Option<Vec<&'static str>> {
    parse_language_name(name).map(|lang| lang.get_extensions().to_vec())
}

/// Resolve a user-supplied language name (as accepted by
/// `analyze_source`) to its `LANG` enum value.
///
/// Matches case-insensitively against [`lang_to_name`]. Helper
/// variants (`Ccomment`, `Preproc`) are *not* exposed through this
/// path — they exist purely to support the C/C++ preprocessing
/// pipeline internally and have no public file extensions, so
/// accepting them as an explicit `language` argument would let
/// callers run them on inputs they were never meant to see.
/// Returns `None` for unknown or internal names; callers map that
/// to `UnsupportedLanguageError` on the Python side.
pub(crate) fn parse_language_name(name: &str) -> Option<LANG> {
    let needle = name.to_lowercase();
    public_languages().find(|lang| lang_to_name(*lang) == needle)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn language_for_file_recognises_rust() {
        assert_eq!(language_for_file(&PathBuf::from("foo.rs")), Some("rust"));
    }

    #[test]
    fn language_for_file_recognises_js_as_javascript() {
        // CLI parity: `bca metrics --output-format json foo.js`
        // reports `"language": "javascript"` (via
        // `Mozjs.get_name()`). The bindings must round-trip the
        // same string so a user reading the CLI output and feeding
        // it back through `analyze_source` does not hit
        // UnsupportedLanguageError.
        //
        // Cover every extension Mozjs registers in `langs.rs`
        // (`[js, jsm, mjs, jsx]`) — missing one is a silent
        // coverage gap (audit finding A2).
        for ext in ["js", "jsm", "mjs", "jsx"] {
            assert_eq!(
                language_for_file(&PathBuf::from(format!("foo.{ext}"))),
                Some("javascript"),
                ".{ext} should resolve to \"javascript\"",
            );
        }
    }

    #[test]
    fn language_for_file_returns_none_for_unknown_extension() {
        assert_eq!(language_for_file(&PathBuf::from("foo.xyz")), None);
    }

    #[test]
    fn language_for_file_returns_none_for_no_extension() {
        assert_eq!(language_for_file(&PathBuf::from("README")), None);
    }

    #[test]
    fn supported_languages_includes_python_and_rust() {
        let langs = supported_languages();
        assert!(langs.contains(&"rust"));
        assert!(langs.contains(&"python"));
        assert!(langs.contains(&"java"));
        // `Mozjs` is exposed under the canonical CLI-display name
        // `"javascript"`, NOT the variant name `"mozjs"`. This is
        // the parity contract — a user who reads `"language":
        // "javascript"` from `bca metrics --output-format json` on
        // a `.js` file can pass that same string back through
        // `analyze_source` and get a result.
        assert!(langs.contains(&"javascript"));
        assert!(
            !langs.contains(&"mozjs"),
            "supported_languages should not advertise the internal variant name"
        );
    }

    #[test]
    fn supported_languages_excludes_helper_variants() {
        let langs = supported_languages();
        // `Ccomment` and `Preproc` are internal helpers for the
        // C/C++ pipeline with no registered extensions.
        assert!(!langs.contains(&"ccomment"));
        assert!(!langs.contains(&"preproc"));
    }

    #[test]
    fn tsx_and_typescript_are_distinct_python_identifiers() {
        // Upstream `LANG::get_name` returns "typescript" for both
        // `Tsx` and `Typescript`, which would collide as a lookup
        // key. The Python bindings carry their own variant-keyed
        // name table to keep them disambiguated.
        let langs = supported_languages();
        assert!(langs.contains(&"tsx"));
        assert!(langs.contains(&"typescript"));
        assert!(matches!(parse_language_name("tsx"), Some(LANG::Tsx)));
        assert!(matches!(
            parse_language_name("typescript"),
            Some(LANG::Typescript)
        ));
        // `.tsx` resolves to the Tsx variant; `.ts` to Typescript.
        assert_eq!(language_for_file(&PathBuf::from("foo.tsx")), Some("tsx"));
        assert_eq!(
            language_for_file(&PathBuf::from("foo.ts")),
            Some("typescript")
        );
    }

    #[test]
    fn language_extensions_round_trips_for_every_supported_language() {
        // Every language in `supported_languages` must have its
        // extension list reachable via `language_extensions(name)`,
        // and each of those extensions must resolve back to the
        // same language via `language_for_file`. This guards
        // against drift between the two Python entry points.
        for lang in supported_languages() {
            let exts = language_extensions(lang)
                .unwrap_or_else(|| panic!("language_extensions({lang}) should be Some"));
            assert!(!exts.is_empty(), "language {lang} has no extensions");
            for ext in exts {
                let path = PathBuf::from(format!("foo.{ext}"));
                assert_eq!(
                    language_for_file(&path),
                    Some(lang),
                    "extension .{ext} did not round-trip to language {lang}",
                );
            }
        }
    }

    #[test]
    fn parse_language_name_is_case_insensitive() {
        assert!(matches!(parse_language_name("rust"), Some(LANG::Rust)));
        assert!(matches!(parse_language_name("RUST"), Some(LANG::Rust)));
        assert!(matches!(parse_language_name("Rust"), Some(LANG::Rust)));
        assert!(parse_language_name("bogus").is_none());
    }

    #[test]
    fn parse_language_name_resolves_javascript_to_mozjs() {
        // `Mozjs` is the variant that handles `.js`/`.jsx`/`.mjs`/
        // `.jsm` and reports `"javascript"` as its display name in
        // CLI output. The bindings must accept that same string,
        // not the internal variant name.
        assert!(matches!(
            parse_language_name("javascript"),
            Some(LANG::Mozjs)
        ));
        assert!(matches!(
            parse_language_name("JavaScript"),
            Some(LANG::Mozjs)
        ));
        // The variant name is *not* exposed — `LANG::Javascript`
        // has no extensions and is filtered out by
        // `public_languages`, so the string "mozjs" does not
        // resolve to any LANG.
        assert!(parse_language_name("mozjs").is_none());
    }

    #[test]
    fn parse_language_name_rejects_internal_helper_variants() {
        // `Ccomment` and `Preproc` are reachable via `LANG::get_name`
        // / the variant name table but exist only to support the
        // internal C/C++ preprocessing pipeline. The Python facade
        // must refuse to expose them via the explicit-language path —
        // otherwise callers could route arbitrary source through
        // them and get nonsense metrics back.
        assert!(parse_language_name("ccomment").is_none());
        assert!(parse_language_name("preproc").is_none());
    }
}
