//! Language detection helpers exposed to Python.
//!
//! These thin wrappers reuse the upstream `LANG` enum and its
//! [`big_code_analysis::get_language_for_file`] helper directly for
//! extension matching — the inverse-lookup table cannot drift between
//! Rust and Python because both call the same macro-generated
//! `get_from_ext`. The *forward* lookup (variant → name) is owned by
//! [`lang_to_name`] in this module: the upstream `LANG::get_name`
//! returns a display string shared across variants (both `Tsx` and
//! `Typescript` report `"typescript"`), so the Python facade carries
//! its own variant-keyed name table to keep the two disambiguated.

use std::path::Path;

use big_code_analysis::{LANG, get_language_for_file};

/// Returns the Python-facing language identifier for `lang`.
///
/// The upstream `LANG::get_name` returns a *display* name shared
/// across variants (e.g. both `LANG::Tsx` and `LANG::Typescript`
/// report `"typescript"`), which makes it ambiguous as a lookup
/// key. The Python bindings use the lowercase Rust variant name
/// instead — every `LANG` value has a unique one, and a few small
/// canonical aliases keep CLI-style names usable:
///
/// - `Mozjs` is exposed as `"mozjs"` (variant name lowercased).
/// - `Tsx` is exposed as `"tsx"`.
/// - `Typescript` is exposed as `"typescript"`.
/// - `Csharp` is exposed as `"csharp"`.
/// - All other variants use their variant name lowercased
///   (`Rust` → `"rust"`, `Java` → `"java"`, …).
pub(crate) fn lang_to_name(lang: LANG) -> &'static str {
    match lang {
        LANG::Bash => "bash",
        LANG::Ccomment => "ccomment",
        LANG::Cpp => "cpp",
        LANG::Csharp => "csharp",
        LANG::Elixir => "elixir",
        LANG::Go => "go",
        LANG::Groovy => "groovy",
        LANG::Java => "java",
        LANG::Javascript => "javascript",
        LANG::Kotlin => "kotlin",
        LANG::Lua => "lua",
        LANG::Mozjs => "mozjs",
        LANG::Perl => "perl",
        LANG::Php => "php",
        LANG::Preproc => "preproc",
        LANG::Python => "python",
        LANG::Ruby => "ruby",
        LANG::Rust => "rust",
        LANG::Tcl => "tcl",
        LANG::Tsx => "tsx",
        LANG::Typescript => "typescript",
    }
}

/// Returns the language name (as accepted by `analyze_source`) that
/// matches `path`'s file extension, or `None` when the extension is
/// not recognised.
///
/// Mirrors [`big_code_analysis::get_language_for_file`] one-to-one —
/// agreement with the Rust side is guaranteed because both call into
/// the same `get_from_ext` table generated by `mk_extensions!`.
pub(crate) fn language_for_file(path: &Path) -> Option<&'static str> {
    get_language_for_file(path).map(lang_to_name)
}

/// Returns the supported language names, in declaration order.
///
/// "Supported" here means the variant exists in the `LANG` enum and
/// has at least one registered file extension. Every variant is
/// always present regardless of the Cargo feature set, so this list
/// does not depend on which grammars were compiled in. Internal
/// helper variants without user-facing files (`Ccomment`, `Preproc`)
/// are filtered out because they cannot be reached through any
/// extension table and accept no user input.
pub(crate) fn supported_languages() -> Vec<&'static str> {
    LANG::into_enum_iter()
        .filter(|lang| !lang.get_extensions().is_empty())
        .map(lang_to_name)
        .collect()
}

/// Returns the file extensions that resolve to `name`, or `None` when
/// `name` is not a recognised language.
///
/// The list is the same one consulted by `get_from_ext` and
/// `get_language_for_file` for the matching variant — every extension
/// here will round-trip through [`language_for_file`].
pub(crate) fn language_extensions(name: &str) -> Option<Vec<&'static str>> {
    parse_language_name(name).map(|lang| lang.get_extensions().to_vec())
}

/// Resolve a user-supplied language name (as accepted by
/// `analyze_source`) to its `LANG` enum value.
///
/// Matches case-insensitively against [`lang_to_name`]. Helper
/// variants (`Ccomment`, `Preproc`) are *not* exposed through this
/// path — they exist purely to support the C/C++ preprocessing
/// pipeline internally and have no public file extensions, so
/// accepting them as an explicit `language` argument would let
/// callers run them on inputs they were never meant to see.
/// Returns `None` for unknown or internal names; callers map that
/// to `UnsupportedLanguageError` on the Python side.
pub(crate) fn parse_language_name(name: &str) -> Option<LANG> {
    let needle = name.to_lowercase();
    LANG::into_enum_iter()
        .filter(|lang| !lang.get_extensions().is_empty())
        .find(|lang| lang_to_name(*lang) == needle)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn language_for_file_recognises_rust() {
        assert_eq!(language_for_file(&PathBuf::from("foo.rs")), Some("rust"));
    }

    #[test]
    fn language_for_file_returns_none_for_unknown_extension() {
        assert_eq!(language_for_file(&PathBuf::from("foo.xyz")), None);
    }

    #[test]
    fn language_for_file_returns_none_for_no_extension() {
        assert_eq!(language_for_file(&PathBuf::from("README")), None);
    }

    #[test]
    fn supported_languages_includes_python_and_rust() {
        let langs = supported_languages();
        assert!(langs.contains(&"rust"));
        assert!(langs.contains(&"python"));
        assert!(langs.contains(&"java"));
    }

    #[test]
    fn supported_languages_excludes_helper_variants() {
        let langs = supported_languages();
        // `Ccomment` and `Preproc` are internal helpers for the
        // C/C++ pipeline with no registered extensions.
        assert!(!langs.contains(&"ccomment"));
        assert!(!langs.contains(&"preproc"));
    }

    #[test]
    fn tsx_and_typescript_are_distinct_python_identifiers() {
        // Upstream `LANG::get_name` returns "typescript" for both
        // `Tsx` and `Typescript`, which would collide as a lookup
        // key. The Python bindings carry their own variant-keyed
        // name table to keep them disambiguated.
        let langs = supported_languages();
        assert!(langs.contains(&"tsx"));
        assert!(langs.contains(&"typescript"));
        assert!(matches!(parse_language_name("tsx"), Some(LANG::Tsx)));
        assert!(matches!(
            parse_language_name("typescript"),
            Some(LANG::Typescript)
        ));
        // `.tsx` resolves to the Tsx variant; `.ts` to Typescript.
        assert_eq!(language_for_file(&PathBuf::from("foo.tsx")), Some("tsx"));
        assert_eq!(
            language_for_file(&PathBuf::from("foo.ts")),
            Some("typescript")
        );
    }

    #[test]
    fn language_extensions_round_trips_for_every_supported_language() {
        // Every language in `supported_languages` must have its
        // extension list reachable via `language_extensions(name)`,
        // and each of those extensions must resolve back to the
        // same language via `language_for_file`. This guards
        // against drift between the two Python entry points.
        for lang in supported_languages() {
            let exts = language_extensions(lang)
                .unwrap_or_else(|| panic!("language_extensions({lang}) should be Some"));
            assert!(!exts.is_empty(), "language {lang} has no extensions");
            for ext in exts {
                let path = PathBuf::from(format!("foo.{ext}"));
                assert_eq!(
                    language_for_file(&path),
                    Some(lang),
                    "extension .{ext} did not round-trip to language {lang}",
                );
            }
        }
    }

    #[test]
    fn parse_language_name_is_case_insensitive() {
        assert!(matches!(parse_language_name("rust"), Some(LANG::Rust)));
        assert!(matches!(parse_language_name("RUST"), Some(LANG::Rust)));
        assert!(matches!(parse_language_name("Rust"), Some(LANG::Rust)));
        assert!(parse_language_name("bogus").is_none());
    }

    #[test]
    fn parse_language_name_rejects_internal_helper_variants() {
        // `Ccomment` and `Preproc` are reachable via `LANG::get_name`
        // / the variant name table but exist only to support the
        // internal C/C++ preprocessing pipeline. The Python facade
        // must refuse to expose them via the explicit-language path —
        // otherwise callers could route arbitrary source through
        // them and get nonsense metrics back.
        assert!(parse_language_name("ccomment").is_none());
        assert!(parse_language_name("preproc").is_none());
    }
}
