// Per-language metric and AST modules deliberately consume the macro-
// generated tree-sitter token enums via `use crate::*` and `use Foo::*`
// inside match expressions — explicit imports would list dozens of
// variants per arm and obscure the per-language token sets that are the
// point of these files. Allowed at the module level rather than per
// function so the per-language impl blocks stay readable.
#![allow(clippy::wildcard_imports, clippy::enum_glob_use)]

use std::path::Path;
use std::sync::Arc;

use crate::alterator::Alterator;
use crate::checker::Checker;
use crate::getter::Getter;
use crate::langs::*;
use crate::node::Ancestors;
use crate::node::Node;
use crate::parser::Filter;
use crate::preproc::PreprocResults;

/// Static identification of a language code tag.
///
/// Implemented by every `XxxCode` type generated by the internal
/// `mk_code!` macro. Crate-internal: reached only through the
/// `pub(crate)` `Parser<T>` plumbing behind the [`crate::Ast`] seam.
pub(crate) trait LanguageInfo {
    /// Tree-sitter base language enum carried by this code tag.
    type BaseLang;

    /// Returns the workspace-level [`LANG`] variant for this code tag.
    fn lang() -> LANG;
}

// Internal language-dispatch trait reached only by the macro-generated
// `Parser<T>` impls in `src/parser.rs` and the `AnyParser` dispatch in
// `src/macros/mod.rs`. It carries the *parse* half of a language: the
// tree plus its `Checker` / `Getter` classifiers. The per-metric
// associated types live on the separate [`crate::MetricSuite`] supertrait
// (#1376), so this half has no dependency on the metric modules. Not
// part of any documented extension contract — metric extraction is
// driven through the public [`crate::Ast`] / [`crate::analyze`] seam,
// not by implementing this trait. See STABILITY.md.
pub(crate) trait ParserTrait {
    type Checker: Alterator + Checker;
    type Getter: Getter;

    fn new(code: Vec<u8>, path: &Path, pr: Option<Arc<PreprocResults>>) -> Self;
    fn root(&self) -> Node<'_>;
    fn code(&self) -> &[u8];
    /// The returned [`Filter`] borrows `self` — the `"function"`
    /// predicate reads the source bytes (#1162).
    fn filters(&self, requested: &[String]) -> Filter<'_>;
}

pub(crate) trait Search<'a> {
    /// Visits every node of the subtree in source order, handing the
    /// action each node's ancestor chain alongside it so a predicate it
    /// applies stays off `Node::parent` (#1088).
    fn act_on_node(&self, action: &mut dyn FnMut(&Node<'a>, Ancestors<'a, '_>));
    fn first_child(&self, pred: fn(u16) -> bool) -> Option<Node<'a>>;
    fn act_on_child(&self, action: &mut dyn FnMut(&Node<'a>));
}
